routes/web.php
<?php


use App\Http\Controllers\AdminController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function (){
    return redirect()->route('admin.dashboard');
});


Route::prefix('admin')->middleware(['auth', 'verified'])->name('admin.')->group(function (){
    Route::get('/', AdminController::class)->name('dashboard');

    Route::get('/companies', [CompanyController::class,'index'])->name('companies');
    Route::get('/companies/add', [CompanyController::class,'add'])->name('companies.add');
    Route::post('/companies', [CompanyController::class,'store'])->name('companies.store');
    Route::get('/companies/edit/{company}', [CompanyController::class,'edit'])->name('companies.edit');
    Route::put('/companies/{company}', [CompanyController::class,'update'])->name('companies.update');
    Route::delete('/companies/{company}', [CompanyController::class,'destroy'])->name('companies.destroy');

    Route::get('/employees', [EmployeeController::class,'index'])->name('employee.index');
    Route::post('/employees', [EmployeeController::class,'store'])->name('employee.store');
    Route::get('/employees/edit/{employee}', [EmployeeController::class,'edit'])->name('employee.edit');
    Route::get('/employees/add', [EmployeeController::class,'add'])->name('employee.add');
    Route::get('/employees/{company}', [EmployeeController::class,'byCompany'])->name('employee.by-company');
    Route::put('/employees/{employee}', [EmployeeController::class,'update'])->name('employee.update');
    Route::delete('/employees/{employee}', [EmployeeController::class,'destroy'])->name('employee.destroy');



});


//Route::get('/admin/companies', [CompanyController::class,'index'])->name('admin');

//Route::middleware('auth')->group(function () {
//    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
//});

require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Company extends Model
{
    use HasFactory;

    protected $guarded = false;
    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class);
    }
    public function logo(): HasOne
    {
        return $this->hasOne(Logo::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use App\Models\Logo;
use App\Services\CompaniesService;
use App\Services\LogoService;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    public function __construct(private CompaniesService $service)
    {
    }

    public function index()
    {
        $companies = Company::paginate(10);
        $heads = $this->service->getHeads();
        $config = $this->service->getConfig($companies);
        return view('companies')->with(['heads' => $heads,'config' => $config,'companies' => $companies]);
    }


    public function add()
    {
        return view('companies.add');
    }

    public function edit(Company $company)
    {
        return view('companies.edit')->with(['company' => $company]);
    }
    public function store(CompanyRequest $request)
    {
        $validated = $request->validated();
        $company = Company::create([
            'name' => $validated['name'],
            'email' => $validated['email'],
            'website' => $validated['website'],
        ]);
        $url = $request->hasFile('file') ? LogoService::getUrl($request->file('file')) : config('app.default_logo');
        Logo::create([
            'url' => $url,
            'company_id' => $company->id
        ]);
        return redirect()->route('admin.companies');
    }



    public function update(CompanyRequest $request, Company $company)
    {
        $validated = $request->validated();
        $company->update([
            'name' => $validated['name'],
            'email' => $validated['email'],
            'website' => $validated['website'],
        ]);
        $url = $request->hasFile('file') ? LogoService::getUrl($request->file('file')) : $company->logo->url;
        $company->logo->update([
            'url' => $url,
            'company_id' => $company->id
        ]);
        return redirect()->route('admin.companies');
    }

    public function destroy(Company $company)
    {
        $company->employees->each->delete();
        $company->delete();

        return back();
    }
}

resources/views/companies/add.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Add Company</h1>
@stop

@section('content')
    {{-- Minimal --}}
    <form action="{{route('admin.companies.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <x-adminlte-input name="name" label="Name" placeholder="Name" fgroup-class="col-md-6"/>
        <x-adminlte-input name="email" label="Email" placeholder="email@email.com" type="email" fgroup-class="col-md-6"/>
        <x-adminlte-input name="website" label="Website" placeholder="example.com" fgroup-class="col-md-6"/>
        <x-adminlte-input-file name="file" igroup-size="sm" placeholder="Choose a file..." fgroup-class="col-md-6">
            <x-slot name="prependSlot">
                <div class="input-group-text bg-lightblue">
                    <i class="fas fa-upload"></i>
                </div>
            </x-slot>
        </x-adminlte-input-file>
        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save" />
    </form>



@stop

@section('css')

@stop

resources/views/companies/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit Company</h1>
@stop

@section('content')
    {{-- Minimal --}}
    <form action="{{route('admin.companies.update',['company' => $company])}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <x-adminlte-input name="name" label="Name" placeholder="Name" fgroup-class="col-md-6" value="{{$company->name}}"/>
        <x-adminlte-input name="email" label="Email" placeholder="email@email.com" type="email" fgroup-class="col-md-6" value="{{$company->email}}"/>
        <x-adminlte-input name="website" label="Website" placeholder="example.com" fgroup-class="col-md-6" value="{{$company->website}}"/>
        <x-adminlte-input-file name="file" igroup-size="sm" placeholder="Choose a file..." fgroup-class="col-md-6">
            <x-slot name="prependSlot">
                <div class="input-group-text bg-lightblue">
                    <i class="fas fa-upload"></i>
                </div>
            </x-slot>
        </x-adminlte-input-file>
        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save" />
    </form>



@stop

@section('css')

@stop