routes/web.php
<?php


use App\Http\Controllers\AdminController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function (){
    return redirect()->route('admin.dashboard');
});


Route::prefix('admin')->middleware(['auth', 'verified'])->name('admin.')->group(function (){
    Route::get('/', AdminController::class)->name('dashboard');

    Route::get('/companies', [CompanyController::class,'index'])->name('companies');
    Route::get('/companies/add', [CompanyController::class,'add'])->name('companies.add');
    Route::post('/companies', [CompanyController::class,'store'])->name('companies.store');
    Route::get('/companies/edit/{company}', [CompanyController::class,'edit'])->name('companies.edit');
    Route::put('/companies/{company}', [CompanyController::class,'update'])->name('companies.update');
    Route::delete('/companies/{company}', [CompanyController::class,'destroy'])->name('companies.destroy');

    Route::get('/employees', [EmployeeController::class,'index'])->name('employee.index');
    Route::post('/employees', [EmployeeController::class,'store'])->name('employee.store');
    Route::get('/employees/edit/{employee}', [EmployeeController::class,'edit'])->name('employee.edit');
    Route::get('/employees/add', [EmployeeController::class,'add'])->name('employee.add');
    Route::get('/employees/{company}', [EmployeeController::class,'byCompany'])->name('employee.by-company');
    Route::put('/employees/{employee}', [EmployeeController::class,'update'])->name('employee.update');
    Route::delete('/employees/{employee}', [EmployeeController::class,'destroy'])->name('employee.destroy');



});


//Route::get('/admin/companies', [CompanyController::class,'index'])->name('admin');

//Route::middleware('auth')->group(function () {
//    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
//});

require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    use HasFactory;

    protected $guarded = false;

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use App\Services\EmployeeService;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function __construct(private EmployeeService $service)
    {
    }

    public function index()
    {
        $employees = Employee::paginate(10);
        $heads = $this->service->getHeads();
        $config = $this->service->getConfig($employees);
        return view('employees')->with(['heads' => $heads,'config' => $config,'employees' => $employees]);
    }


    public function byCompany(Company $company)
    {
        $employees = $company->employees()->paginate(10);
        $heads = $this->service->getHeads();
        $config = $this->service->getConfig($employees);
        return view('employees')->with(['heads' => $heads,'config' => $config,'employees' => $employees]);
    }


    public function store(EmployeeRequest $request)
    {
        $validated = $request->validated();
        //dd($validated);
        $employee = Employee::create([
            'first_name' => $validated['first_name'],
            'last_name' => $validated['last_name'],
            'company_id' => Company::findOrFail($validated['company_id'])->id,
            'email' => $validated['email'],
            'phone' => $validated['phone'],
        ]);
        return redirect()->route('admin.employee.index');
    }


    public function add()
    {
        return view('employees.add');
    }
    public function edit(Employee $employee)
    {
        return view('employees.edit')->with(['employee' => $employee]);
    }

    public function update(EmployeeRequest $request, Employee $employee)
    {
        $validated = $request->validated();
        $employee->update([
            'first_name' => $validated['first_name'],
            'last_name' => $validated['last_name'],
            'company_id' => Company::findOrFail($validated['company_id'])->id,
            'email' => $validated['email'],
            'phone' => $validated['phone'],
        ]);
        return redirect()->route('admin.employee.index');
    }

    public function destroy(Employee $employee)
    {
        $employee->delete();

        return back();
    }
}

resources/views/employees/add.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Add Company</h1>
@stop

@section('content')
    {{-- Minimal --}}
    <form action="{{route('admin.employee.store')}}" method="post">
        @csrf
        <x-adminlte-input name="first_name" label="First Name" placeholder="Jone" fgroup-class="col-md-6"/>
        <x-adminlte-input name="last_name" label="Last Name" placeholder="Doe" fgroup-class="col-md-6"/>
        @php
        $companies = \App\Models\Company::all();
        $options = [];
        foreach ($companies as $company){
            $options[$company->id] = $company->name;
        }
//        $options->toArray();
        @endphp
        <x-adminlte-select name="company_id" fgroup-class="col-md-6">
            <x-adminlte-options :options="$options"/>
        </x-adminlte-select>
        <x-adminlte-input name="email" label="Email" placeholder="email@email.com" type="email"
                          fgroup-class="col-md-6"/>
        <x-adminlte-input name="phone" label="Phone Number" placeholder="+380 98 735 85 48" fgroup-class="col-md-6"/>
        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
    </form>

@stop

@section('css')

@stop

resources/views/employees/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit Employee <b>{{$employee->first_name}} {{$employee->last_name}}</b></h1>
@stop

@section('content')
    {{-- Minimal --}}
    <form action="{{route('admin.employee.update',['employee' => $employee])}}" method="post">
        @csrf
        @method('PUT')
        <x-adminlte-input name="first_name" label="First Name" placeholder="Jone" fgroup-class="col-md-6" value="{{$employee->first_name}}"/>
        <x-adminlte-input name="last_name" label="Last Name" placeholder="Doe" fgroup-class="col-md-6" value="{{$employee->last_name}}"/>
        @php
            $companies = \App\Models\Company::all();
            $options = [];
            foreach ($companies as $company){
                $options[$company->id] = $company->name;
            }
    //        $options->toArray();
        @endphp
        <x-adminlte-select name="company_id" fgroup-class="col-md-6">
            <x-adminlte-options :options="$options" selected="{{$employee->company->id}}"/>
        </x-adminlte-select>
        <x-adminlte-input name="email" label="Email" placeholder="email@email.com" type="email"
                          fgroup-class="col-md-6" value="{{$employee->email}}"/>
        <x-adminlte-input name="phone" label="Phone Number" placeholder="+380 98 735 85 48" fgroup-class="col-md-6" value="{{$employee->phone}}"/>
        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
    </form>



@stop

@section('css')

@stop